name-template: 'Release $NEXT_VERSION 🚀'
tag-template: 'v$NEXT_VERSION'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '-'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: '🚀 Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '♻️ Refactor'
    labels:
      - refactor
  - title: '📚 Docs'
    labels:
      - documentation
  - title: '⚡ Performances'
    labels:
      - documentation

version-resolver:
  major:
    labels:
      - breaking-change
  minor:
    labels:
      - feature
  patch:
    labels:
      - bug
      - refactor
      - documentation
  default: patch
