name-template: 'Release $NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🧹 Chores'
    labels:
      - chore
  - title: '📦 Releases'
    labels:
      - release
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: ['-']