services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment: # Variables d'environnement pour configurer PostgreSQL
      POSTGRES_USER: postgres # Nom d'utilisateur de la base de données
      POSTGRES_PASSWORD: postgres # Mot de passe pour l'utilisateur
      POSTGRES_DB: taskora # Nom de la base de données initiale à créer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taskora-net # Attache PostgreSQL au réseau personnalisé 'taskora-net'

  # Service Spring Boot (application principale)
  spring-app:
    image: taskora-back-local
    container_name: spring-app-container
    build:
      context: .
    restart: always
    depends_on:
      - postgres # Assure que PostgreSQL démarre avant l'application Spring Boot
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8080:8080"
    networks:
      - taskora-net

networks:
  taskora-net:
    driver: bridge # Driver réseau permettant aux conteneurs de communiquer entre eux
volumes:
  pgdata: