spring:
  application:
    name: taskora-back
  datasource:
    url: jdbc:postgresql://localhost:5432/taskora
    username: taskora_user
    password: taskora_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
