name: Auto-label Pull Request based on Commit Message

on:
  pull_request:
    types:
      - opened
      - synchronize # Quand une PR est mise à jour avec de nouveaux commits

permissions:
  contents: read
  pull-requests: write # Donne la permission de gérer les PRs, notamment d'ajouter des labels

jobs:
  auto_label:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt (inclus dans toutes les branches associées à la PR)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Clone complet requis pour accéder aux commits

      # Étape 2 : Analyser le message du dernier commit spécifique à la branche source
      - name: Extract labels from source branch commit
        id: extract-labels
        run: |
          echo "Analyzing the latest commit from the source branch..."

          # Récupérer le hash du HEAD de la branche source
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          echo "Source Branch Commit SHA: $COMMIT_SHA"

          # Récupérer le message lié au commit
          LAST_COMMIT_MESSAGE=$(git show --pretty=format:%s --no-patch $COMMIT_SHA)
          echo "Last Commit Message: $LAST_COMMIT_MESSAGE"

          # Extraire les labels (motifs commençant par '#')
          LABELS=$(echo "$LAST_COMMIT_MESSAGE" | grep -o "#[a-zA-Z0-9_-]*" | tr -d "#")
          echo "Extracted Labels: $LABELS"

          # Sauvegarder les labels extraits dans l'environnement GitHub
          echo "labels=$LABELS" >> $GITHUB_ENV

      # Étape 3 : Ajouter les labels extraits à la PR
      - name: Add labels to the Pull Request
        if: env.labels != ''
        run: |
          echo "Adding labels to the Pull Request: $LABELS"

          # Construire un tableau JSON attendu par l'API GitHub
          LABEL_ARRAY=$(echo "$LABELS" | jq -R -s 'split("\n")[:-1]')
          echo "{ \"labels\": $LABEL_ARRAY }" > labels.json
          cat labels.json

          # Utiliser l'API GitHub REST v3 pour ajouter les labels
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @labels.json \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"
