name: Auto-label Pull Request based on Commit Message

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  auto_label:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Étape 2 : Extraire les labels
      - name: Extract labels from source branch commit
        id: extract-labels
        run: |
          echo "Analyzing the latest commit from the source branch..."
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          echo "Source Branch Commit SHA: $COMMIT_SHA"

          LAST_COMMIT_MESSAGE=$(git show --pretty=format:%s --no-patch $COMMIT_SHA)
          echo "Last Commit Message: $LAST_COMMIT_MESSAGE"

          # Extraire et nettoyer les labels
          LABELS=$(echo "$LAST_COMMIT_MESSAGE" | grep -o "#[a-zA-Z0-9_-]*" | tr -d "#" | xargs | sed 's/ /,/g')

          # Vérifier si des labels ont été extraits
          if [ -z "$LABELS" ]; then
            echo "No valid labels found. Skipping label application."
            exit 0
          fi

          echo "Extracted Labels: $LABELS"
          echo "labels=$LABELS" >> $GITHUB_ENV

      # Étape 3 : Ajouter les labels à la PR
      - name: Add labels to the Pull Request
        if: env.labels != ''
        run: |
          echo "Adding labels to the Pull Request: $LABELS"
          
          # Créer un tableau JSON pour les labels
          LABEL_ARRAY=$(echo "$LABELS" | jq -R -s 'split(",") | map(select(length > 0))')
          echo "{ \"labels\": $LABEL_ARRAY }" > labels.json
          cat labels.json

          # Envoyer la requête à l'API GitHub
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @labels.json \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"