name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: aassalax/workflows/.github/workflows/kt/build-and-publish.yml@main
