name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build the project and generate the JAR
      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      # Define custom Docker tag
      - name: Define Docker Tag
        id: generate_tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          DATE=$(date +'%Y%m%d')
          echo "TAG=dev-${DATE}-${SHORT_SHA}" >> $GITHUB_ENV


      # Build the Docker image, en copiant le JAR généré
      - name: Build Docker image
        run: docker build -t ghcr.io/projex-io/taskora-back:${{ env.TAG }} .

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the image
      - name: Push Docker image
        run: docker push ghcr.io/projex-io/taskora-back:${{ env.TAG }}