name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Define Docker Tag (dev version)
        id: generate_tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          DATE=$(date +'%Y%m%d')
          echo "TAG=dev-${DATE}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}

          echo "🔧 Building Docker image: $IMAGE:${{ env.TAG }} and $IMAGE:latest"
          docker build -t $IMAGE:${{ env.TAG }} .
          docker tag $IMAGE:${{ env.TAG }} $IMAGE:latest
          docker push $IMAGE:latest