name: CI (Pull Request)

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew assemble --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: build/test-results/test/*.xml
          reporter: junit