name: Run workflow based on PR label

on:
  pull_request:
    types:
      - labeled

jobs:
  check_label_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check PR labels and set action
        run: |
          LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
            | jq -r '.[].name')

          echo "Labels found: $LABELS"

          run_action="none"

          while IFS= read -r label; do
            case "$label" in
              question) echo "Found label 'question'"; run_action="question" ;;
              bug) echo "Found label 'bug'"; run_action="bug" ;;
              feature) echo "Found label 'feature'"; run_action="feature" ;;
              no-draft) echo "Found label 'no-draft'"; run_action="no-draft" ;;
              refactor) echo "Found label 'refactor'"; run_action="refactor" ;;
            esac
          done <<< "$LABELS"

          echo "run_action=$run_action" >> $GITHUB_ENV

      - name: Run task for 'question' label
        if: env.run_action == 'question'
        run: echo "Executing task for 'question' label"

      - name: Run task for 'bug' label
        if: env.run_action == 'bug'
        run: echo "Executing task for 'bug' label"

      - name: Run task for 'feature' label
        if: env.run_action == 'feature'
        run: echo "Executing task for 'feature' label"

      - name: Run task for 'no-draft' label
        if: env.run_action == 'no-draft'
        run: echo "Executing task for 'no-draft' label"

      - name: Run task for 'refactor' label
        if: env.run_action == 'refactor'
        run: echo "Executing task for 'refactor' label"
